##### THIS ALLOWS US TO DEPLOY THE SITE FROM A GIT REPO ######
---
deployment:
  tasks:
    - export DEPLOYPATH=/home/pluniwcv/public_html/memex/
    - /bin/cp -r /home/pluniwcv/repositories/memex/* $DEPLOYPATH
